version: '3.8'

services:

  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy
    depends_on:
        - frontend
        - julia-backend
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf

  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./frontend
      target: dev
    restart: on-failure

  julia-backend:
    image: julia-backend
    container_name: julia_backend
    build:
      context: ./backend/AtlasBackend
      target: dev
    restart: on-failure
