version: '3.8'

services:

  reverse-proxy:
    ports:
      - 8081:80
      - 8888:8888

  frontend:
    volumes:
      - ./frontend:/app
    ports:
      - 3001:3000

  jupyter-backend:
    volumes: 
      - ./backend/JupyterBackend:/home/jovyan/work
    ports:
      - 8001:8888
