version: '3.8'

services:

  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf

  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./frontend
      target: dev
    restart: on-failure

  jupyter-backend:
    image: jupyter-backend
    container_name: jupyter_backend
    build:
      context: ./backend/JupyterBackend
      target: dev
    restart: on-failure
