version: '3.8'

services:

  reverse-proxy:
    ports:
      - 8080:80

  frontend:
    build:
      target: prod
    ports:
      - 3000:3000

  julia-backend:
    build:
      target: prod
    ports:
      - 8000:8000
