include("./TestUtils.jl")
include("./utils/kernels/execution/ExecuterTest.jl")
include("./utils/parser/TokensTest.jl")
include("./AtlasGraphTest.jl")
include("./utils/interactions/JsonUtilsTest.jl")
include("./utils/algorithms/FormulaUtilsTest.jl")
include("./utils/interactions/EndpointsTest.jl")
include("./functions/MathTest.jl")
