include("./TestUtils.jl")
include("./utils/parser/AtlasParserTest.jl")
include("./utils/interactions/TypesTest.jl")
include("./utils/interactions/JsonUtilsTest.jl")
include("./utils/algorithms/FormulaUtilsTest.jl")
include("./AtlasGraphTest.jl")
include("./utils/interactions/EndpointsTest.jl")
